### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by rthomazel** [develop-mental-llc/create-react-admin-amplify-app#4]
I went along with typescript for now, since I'm used to that. Hope it isn't a problem and we can generate the js from it anyway.

**Comment by DCarper** [comment]
I haven't used it before, for sure okay with _craaa_ using it but at this point I don't think it should generate a typescript app.

That feels like a design decision that is beyond the scope of _craaa_. There's people like me who don't know it and would consider it a barrier to adoption if not a blocker.

What do you think?

**Comment by DCarper** [comment]
Glad we ended up going with it for the repo, gonna close this out
